tasks:
  - init: |
      mkdir downloads
      cd downloads
      python -m pip install --upgrade pip
      python -m pip install -e .[testing]
      python -m pip install -r requirements-dev.txt
      source ~/.bashrc
      pre-commit install
