name: Python Benchmarks
on:
  push:
    branches:
      - main
jobs:
  benchmark:
    runs-on: ubuntu-latest
    if: ${{ github.repository }} == 'histolab/histolab'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Run Benchmarks
        run: |
          sudo apt install -y openslide-tools
          pip install numpy pytest pytest-benchmark requests
          pip install -e .
          pytest tests/benchmarks/test_benchmarks.py --benchmark-json output.json
      # Download previous benchmark result from cache (if exists)
      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Python Benchmark with pytest-benchmark
          tool: 'pytest'
          output-file-path: output.json
          # Personal access token to deploy GitHub Pages branch
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          # Push and deploy GitHub pages branch automatically
          auto-push: true
          fail-on-alert: true
          comment-on-alert: true
          alert-comment-cc-users: '@ernestoarbitrio'
          alert-threshold: '300%'
